# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-07 18:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0002_auto_20161206_1554'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject',
            name='description',
            field=models.CharField(max_length=255),
        ),
    ]
