# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-12 09:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_public_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='location',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
