# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-12 09:59
from __future__ import unicode_literals

from django.db import migrations
import stdimage.models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_user_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='image',
            field=stdimage.models.StdImageField(blank=True, null=True, upload_to='images/user_profiles'),
        ),
    ]
