# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-27 08:12
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('make', models.CharField(max_length=30)),
                ('model', models.CharField(max_length=30)),
                ('colour', models.CharField(max_length=20)),
                ('year_of_manufacture', models.CharField(max_length=4)),
                ('cylinder_capacity', models.CharField(max_length=6)),
                ('transmission', models.CharField(max_length=10)),
                ('fuel_type', models.CharField(max_length=10)),
                ('co2', models.CharField(max_length=10)),
                ('doors', models.IntegerField(max_length=2)),
                ('dateAdded', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
