# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-05 12:43
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('exclude_from_collation', models.BooleanField(default=False)),
                ('exclude_from_collation_reason', models.CharField(max_length=30, null=True)),
                ('make', models.CharField(max_length=30)),
                ('model', models.CharField(max_length=30)),
                ('sub_model', models.CharField(max_length=30, null=True)),
                ('colour', models.CharField(max_length=20)),
                ('year_of_manufacture', models.CharField(max_length=10)),
                ('cylinder_capacity', models.CharField(max_length=10)),
                ('transmission', models.CharField(max_length=10)),
                ('fuel_type', models.CharField(max_length=10)),
                ('co2', models.CharField(max_length=10)),
                ('doors', models.CharField(max_length=10)),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/cars')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Refuel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_time_added', models.DateTimeField(auto_now_add=True)),
                ('litres', models.DecimalField(decimal_places=2, max_digits=10)),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('odometer', models.DecimalField(decimal_places=2, max_digits=12)),
                ('full_tank', models.BooleanField()),
                ('missed_refuels', models.BooleanField()),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cars.Car')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
