# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-06 15:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='refuel',
            name='date',
            field=models.DateTimeField(null=True),
        ),
    ]
