# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-06 17:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0002_refuel_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='doors',
            field=models.CharField(max_length=2),
        ),
    ]
