# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-27 08:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0002_remove_car_doors'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='economy_average',
            field=models.DecimalField(decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='car',
            name='economy_latest',
            field=models.DecimalField(decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='car',
            name='fuel_price_average',
            field=models.DecimalField(decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='car',
            name='price_per_mile_average',
            field=models.DecimalField(decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='car',
            name='refuels',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='car',
            name='total_fuel_expenditure',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='car',
            name='total_fuel_litres',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='car',
            name='total_mileage_tracked',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
