# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-27 08:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0003_auto_20161127_0833'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='doors',
            field=models.CharField(default=4, max_length=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='car',
            name='cylinder_capacity',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='car',
            name='year_of_manufacture',
            field=models.CharField(max_length=10),
        ),
    ]
