# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-06 17:42
from __future__ import unicode_literals

from django.db import migrations
import stdimage.models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0003_auto_20161206_1735'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='image',
            field=stdimage.models.StdImageField(blank=True, null=True, upload_to='images/cars'),
        ),
    ]
