# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-27 13:10
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0004_auto_20161127_0848'),
    ]

    operations = [
        migrations.RenameField(
            model_name='car',
            old_name='dateAdded',
            new_name='date_added',
        ),
    ]
